### ISSUE TITLE
[비자 테스트] > 비자 테스트 페이지 UI

### ISSUE THREAD

**Issue by Rory0304** [Rory0304/kowork_clone#6]
### Todo
- [x] D-10-1 구직 비자 테스트 페이지 제작
- [x] F-2-7 거주 비자 테스트 페이지 제작
- [x] 점수 Alert 
- [x] Progress Bar
- [x] 기준 요건 업데이트 알림
